In [1]:
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
import pandas as pd

In [3]:
documents = [

    "I love NLP",
    "NLP is fun",
    "I love AI"
]

In [4]:
 cvec = CountVectorizer(token_pattern='(?u)\\b\\w+\\b')

In [5]:
bow_matrix = cvec.fit_transform(documents)

In [6]:
bow_matrix

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [7]:
bow_array = bow_matrix.toarray()

In [8]:
bow_array

array([[0, 0, 1, 0, 1, 1],
       [0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0]], dtype=int64)

In [9]:
pd.DataFrame(bow_array,columns= cvec.get_feature_names_out())

   ai  fun  i  is  love  nlp
0   0    0  1   0     1    1
1   0    1  0   1     0    1
2   1    0  1   0     1    0

In [11]:
cvec.get_feature_names_out()

array(['ai', 'fun', 'i', 'is', 'love', 'nlp'], dtype=object)

In [13]:
X_new = cvec.transform(["NLP is amazing"])

In [14]:
X_new.toarray()

array([[0, 0, 0, 1, 0, 1]], dtype=int64)

In [15]:
pd.DataFrame(X_new.toarray(), columns=cvec.get_feature_names_out())

   ai  fun  i  is  love  nlp
0   0    0  0   1     0    1